[rule.SPOTIPY_SECRET]
description = "Spotipy secret environment variable"
regex = '''SPOTIPY_[A-Z_]*=[\"']?[A-Za-z0-9+/=]{32,}'''
secret = true

[allowlist]
# Add any allowed patterns here

# Standard rules
[[rules]]
description = "Generic Credential"
regex = '''(?i)(password|passwd|pwd|secret|token|api[_-]?key|access[_-]?key|private[_-]?key)[\"']?\s*[:=]\s*[\"']?[A-Za-z0-9+/=]{32,}'''
secret = true

[[rules]]
description = "AWS Access Key ID"
regex = '''AKIA[0-9A-Z]{16}'''
secret = true

[[rules]]
description = "AWS Secret Access Key"
regex = '''(?i)aws(.{0,20})?(?-i)['\"][0-9a-zA-Z/+]{40}['\"]'''
secret = true

# Add more standard rules as needed
