repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.27.2
    hooks:
      - id: gitleaks
        args: ["--config=.gitleaks.toml"]
        stages: [pre-commit]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      - id: ruff
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: D:/GitRepos/yt_to_spotifyplaylist/.venv/Scripts/pytest.exe
        language: system
        types: [python]
        pass_filenames: false
