version: "3.8"

services:
  backend:
    build:
      context: ../FastAPI
      dockerfile: Dockerfile
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vite-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://backend:8000
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
