name: CI

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install package and all dev dependencies
        run: |
          pip install .[dev]
      - name: Install extra tools
        run: |
          pip install ruff mypy types-toml pytest-asyncio
      - name: Lint with ruff
        run: |
          ruff check .
      - name: Type check with mypy (strict)
        run: |
          mypy --strict yt2spotify
      - name: Run tests (quiet)
        run: |
          pytest -q
