name: CI

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          pip install .[dev]
      - name: Install package in editable mode
        run: |
          pip install -e .
      - name: Lint with ruff
        run: |
          ruff check .
      - name: Type check with mypy
        run: |
          mypy yt2spotify
      - name: Generate dryrun output files
        run: |
          python -m yt2spotify.cli sync "https://www.youtube.com/playlist?list=PLE4B85EC96395A67D" "53nCceptoTItuwCWUIAlXr" --dry-run --no-progress
      - name: Ensure dryrun output files exist
        run: |
          mkdir -p output/dryrun_temp
          for f in dryrun_added.json all_youtube_entries.json all_results.json not_found_songs.json private_deleted_songs.json; do
            if [ ! -f "output/dryrun_temp/$f" ]; then
              echo "[]" > "output/dryrun_temp/$f"
            fi
          done
      - name: Run tests
        run: |
          pytest
      - name: Run coverage checks
        run: |
          pytest --cov=yt2spotify --cov-report=term-missing
          coverage report --fail-under=80
          coverage report --include="yt2spotify/core.py" --fail-under=70
