name: CI

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install package and all dev dependencies
        run: |
          pip install .[dev]
      - name: Install extra tools
        run: |
          pip install ruff mypy types-toml pytest-asyncio
      - name: Lint with ruff
        run: |
          ruff check .
      - name: Type check with mypy (strict)
        run: |
          mypy --strict yt2spotify
      - name: Ensure dryrun output files exist
        run: |
          mkdir -p output/dryrun_temp
          for f in dryrun_added.json all_youtube_entries.json all_results.json not_found_songs.json private_deleted_songs.json; do
            if [ ! -f "output/dryrun_temp/$f" ]; then
              echo "[]" > "output/dryrun_temp/$f"
            fi
          done
      - name: Run tests (quiet)
        run: |
          pytest -q
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: 2ec9a605-c6cc-47cc-a935-06c9b9a90ca0
