name: CI

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt
      - name: Install package in editable mode
        run: |
          pip install -e .
      - name: Lint with ruff
        run: |
          ruff check .
      - name: Type check with mypy
        run: |
          mypy yt2spotify
      - name: Run tests
        run: |
          pytest
      - name: Run coverage checks
        run: |
          pytest --cov=yt2spotify --cov-report=term-missing
          coverage report --fail-under=80
          coverage report --include="yt2spotify/core.py" --fail-under=70
      - name: Validate JSON/CSV outputs
        run: |
          PYTHONPATH=. pytest --cov=yt2spotify tests/test_json_csv_validation.py --cov-report=term-missing
